### ISSUE TITLE
What version of Nao-meshes for indigo should be used?

### ISSUE THREAD

**Issue by robodave94** [osrf/robocup_3d_simulation#8]
Hi,

Thanks for this project as it has been extremely helpful to me? I have managed to get it working for the most part but I am getting an error with the NAO meshes package with gazebo and I think it is because the meshes package for indigo has been updated more recently than this project, I was wondering if you could confirm for me what version of the NAO meshes package does this simulation work with?

Cheers.

**Comment by caguero** [comment]
hi,

If I remember correctly we were including our own copy of the meshes in the robocup3ds package. The ros-*-nao-meshes package is not used. This solution is far from optimal but it was an easy way to have blue and red meshes for the players. What is the error that you're getting?

**Comment by robodave94** [comment]
ah ok, that makes sense, the error I'm encountering must be being caused by something else then. On ubuntu trusty, I use the quick install script and install ros desktop as the roscore option is missing from the quick script installation. Everything else is there though. Once installed and I have gazebo running I attempt to run spawnTeams and the following error appears in the gazebo terminal and the players in gazebo, while created, do not work optimally when proceeding with other commands
![screenshot from 2017-02-14 14 37 53](https://cloud.githubusercontent.com/assets/14812745/22914203/6321ddfe-f2c3-11e6-8caa-0f0449acd48f.png)
, it has something to do with the soccer sdf file i think, any input would be appreciated.

Thanks

**Comment by caguero** [comment]
By the way, we moved this project to [bitbucket](https://bitbucket.org/osrf/robocup3ds) and made a lot of improvements there. Could you give it a try? It should work much better.
